### PR TITLE
refactor(InformationController): Pass in RunImpl run instead of Long runId

### LINKED ISSUE #60: Pass in RunImpl run to Controller param instead of Long runId
### Description

Use Spring's DomainClassConverter so we don't need to pass in runId and look it up using RunService. Spring should automatically look it up using the RunRepository

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Added RunRepository and new bean names to make use of Spring's DomainClassConverter. Read more about it [here](https://www.baeldung.com/spring-data-web-support#3-the-controller-layer)
- Changed getConfig endpoints for teacher CM and student Run in InformationController to take in RunImpl instead of Long. This reduces the need to write code to look up the Run object from the database. It is done automatically by the DomainClassConverter.

## Test
- Endpoints to retrieve config still work for:
   - Student Run: /api/config/studentRun/[RUN_ID]
   - Teacher CM: /api/config/classroomMonitor/[RUN_ID]
- Opening student run (VLE) and teacher grading tool (CM) still work as before; it gets the config correctly and load properly.

Closes #60

### CODE REVIEW

**Comment by geoffreykwan** [comment]
Works well.

Should we do it for the Authoring Tool config endpoint too to cover all 3 main views?

https://github.com/WISE-Community/WISE-API/blob/c61c556d60bdc10ec8bfbfa6ad6d7bb9474cc211/src/main/java/org/wise/portal/presentation/web/controllers/author/project/AuthorAPIController.java#L373-L378

**Comment by hirokiterashima** [comment]
I'll do it in a separate issue. This one is for RunImpl, just to get our feet wet and make sure that everything works.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
