### PR TITLE
Importing a step or component that contains an asset with a space in the file name does not import the asset

### LINKED ISSUE #16: Importing a step or component that contains an asset with a space in the file name does not import the asset
This file will be imported Green-stem-plant.jpg.
This file will not be imported "Green stem plant.jpg" (in the unit content it will be referenced as (Green%20stem%20plant.jpg").

### PR DESCRIPTION
**Pull request by geoffreykwan**
1. Open a unit in the Authoring Tool.
2. Import a step or component that contains a reference to an image that contains a space in the image file name.
3. The image asset should be copied to your project. Previously it would not copy the image asset to your project.

Closes #16

### CODE REVIEW

**Comment by hirokiterashima** [comment]
I'm not able to duplicate the original issue. I've tried adding an image with a space in the filename to html as well as MC choice, and they are imported correctly.

Is there a specific component that's causing this behavior?

**Comment by geoffreykwan** [comment]
You can test it by importing the first step in the [Investigating Planetary Motion & Seasons](https://wise.berkeley.edu/preview/unit/30191/node1) unit. The html content refers to the image file as Man%20Detective%20Eye.jpg.

**Comment by hirokiterashima** [comment]
After discussion, we decided to refactor the importSteps() function by extracting the code to find file names that are referenced by the steps into a separate function. Inside this new function, we will replace "%20" with " ". This way it won't affect the rest of the step content.

**Review by hirokiterashima — APPROVED** [review]
Looks good.

**Pull request merged**
