### PR TITLE
feat(PeerChat): Group students randomly

### LINKED ISSUE #93: PeerChat: group students randomly
### Description

When students get to the Peer Chat activity, group them up randomly once the completion threshold has been met.

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Test
1. As author, create a PeerChat step with 
   - Group Logic Name = "Random"
   - Step and component to be completed ("componentA")
Screen Shot 2022-01-31 at 12 31 24 PM

2. Make sure the component to be completed has a submit button
3. As student, complete componentA and go to the PeerChat step. You should be randomly paired with another student who has completed componentA.

Closes #93

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
1. The getRandomElement() function seems inefficient.

Every time it's called it uses the same possibleMembers set that never shrinks so it can return the same element multiple times.

For example if
maxMembershipCount = 2
possibleMembers = workgroup1, workgroup2, workgroup3

First call to getRandomElement(possibleMembers) returns workgroup1
Second call to getRandomElement(possibleMembers) returns workgroup1
Third call to getRandomElement(possibleMembers) returns workgroup2

The workgroup requesting the grouping is also added to the members set but is also an element in the possibleMembers set which can lead to more unnecessary calls to getRandomElement().

Maybe we should do something like get a list of the possibleMembers and then remove the workgroup making the request from that list and then randomly choose an index in the list and remove the possibleMember that is chosen from the list and repeat if necessary.

2. If there is only one workgroup left, it gets placed in a Peer Group by itself. This is just a result of previous logic we implemented. Do we still want to do this?

**Comment by hirokiterashima** [comment]
1. Good point. I handled this by removing randomly selected workgroup from future consideration.
2. Yes, this is the intended behavior. The teacher can also use the Manage Peer Groups view to make further changes.

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
1. The workgroup that originally created the request should be removed from the possibleMembers to avoid getting randomly selected.

2. Would it be more efficient to turn the possibleMembers set into a list and then randomly choose a number within the length of the list and remove that element from the list? Right now an iterator is created and looped through every time a random member is chosen which seems less efficient.

**Comment by hirokiterashima** [comment]
I think I know what you mean, but just to be clear, can you make a code change suggestion?

**Comment by geoffreykwan** [comment]
Here's what I was thinking of.

```
  private Set<Workgroup> getWorkgroupsInPeerGroupUpToMaxMembership(Workgroup workgroup,
      PeerGroupActivity activity, Set<Workgroup> possibleMembers) throws JSONException {
    Set<Workgroup> members = new HashSet<Workgroup>();
    members.add(workgroup);
    possibleMembers.remove(workgroup); // I added this line
    if (activity.getLogicName().equals("random")) {
      addMembersRandomly(activity, possibleMembers, members);
    } else {
      addMembersInOrder(activity, possibleMembers, members);
    }
    return members;
  }

  // I modified this function
  private void addMembersRandomly(PeerGroupActivity activity, Set<Workgroup> possibleMembers,
      Set<Workgroup> members) {
    List<Workgroup> possibleMembersList = new ArrayList<Workgroup>(possibleMembers);
    Random random = new Random();
    while (members.size() < activity.getMaxMembershipCount()) {
      int randomInt = random.nextInt(possibleMembersList.size());
      Workgroup randomWorkgroup = possibleMembersList.get(randomInt);
      members.add(randomWorkgroup);
      possibleMembersList.remove(randomWorkgroup);
    }
  }
```

**Comment by hirokiterashima** [comment]
@geoffreykwan I made the code changes and they seem to work fine. Can you test again?

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
