### PR TITLE
build(Spring-Boot): Upgrade from 2.3.2 to 2.4.13

### LINKED ISSUE #70: Upgrade Spring-Boot dependency from 2.3.2 to 2.4.13

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Upgrade jedis 3.1.0->3.7.0 and restarting Redis
- Break up websocket endpoints into their own controllers

## Test
- Run mvn clean compile install to download dependencies
- Restart redis to remove any existing sessions
- Make sure that basic functionalities work
- Make sure that websocket features work: pause/unpause screens, lock/unlock lessons

Closes #70

### CODE REVIEW

**Review by breity — APPROVED** [review]
Looks good.

I had to remove the 'target' folder with sudo on Windows (using WSL). Otherwise, `mvn clean` would fail due to a permissions issue ('target' owned by root).

**Comment by geoffreykwan** [comment]
When I try to go to the admin page I see this error page. I don't see any errors in the server logs though. Can you guys reproduce this error? If I switch back to the develop branch, the admin page works.

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Dec 09 17:46:05 UTC 2021
There was an unexpected error (type=Forbidden, status=403).
Forbidden
```

**Review by breity — CHANGES_REQUESTED** [review]
I get the same error that @geoffreykwan does when trying to view /admin.

**Comment by hirokiterashima** [comment]
Good catch! I fixed the issue.

**Comment by breity** [comment]
@hirokiterashima Cool, I can navigate to /admin now and use the admin tools. But when I sign in as another user, the redirect to the homepage fails.

EDIT: Ah, the redirect doesn't work on the develop branch either. I'll approve this now.

**Review by breity — APPROVED** [review]

**Comment by hirokiterashima** [comment]
@breity thanks for finding this issue. I fixed it and the redirect works now.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
