### PR TITLE
refactor(Controllers): Pass in domain instead of Long to methods

### LINKED ISSUE #64: Pass in domain objects to Controller method params instead of Long runId
Use Spring's DomainClassConverter so we don't need to pass in [runId/projectId/workgroupId...] and look it up using [Run/Project/Workgroup...]Service. Spring should automatically look it up using the [Run/Project/Workgroup...]Repository.

- TeacherRunAPIController
	- getStudentStatus
	- sendNodeToPeriod
- AchievementController
	- getWISE5StudentAchievements
	- saveAchievement
- NotificationController
	- getNotifications
	- saveNotification
	- dismissNotification
- NotebookController
	- getNotebookItems
	- getNotebookItems
	- copyNotebookItem
	- saveNotebookItem
	- addNotebookItemToGroup
	- removeNotebookItemFromGroup
- AuthorAPIController
	- copyProject
	- saveProject
	- getAuthorProjectConfig
	- notifyAuthorBeginEnd
- ProjectAPIController
	- getProjectInfo
- ExportProjectController
   - exportProject

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Added ProjectRepository and WorkgroupRepository
- Updated tests

## Test
- Student VLE
   - save achievement (e.g. completing c-rater milestone item should enter new row in db)
   - save notification: post reply to discussion post
   - get notification: open vle
   - dismiss notification
   - Notebook
      - get/create/edit notebook items
- CM
   - retrieve achievement (e.g. open teacher report view)
- AT
   - getAuthorProjectConfig (load AT)
   - notifyAuthorBeginEnd (open/close project authoring)
   - export project
   - copyProject
   - saveProject

Closes #64

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
Get notification when the student opens the VLE doesn't work anymore. I think this is because the logic was changed in NotificationController.getNotifications().

Before when it was working there is an "else if".
```
    if (toWorkgroupId != null) {
      Workgroup workgroup = workgroupService.retrieveById(new Long(toWorkgroupId));
      if (isStudentAndNotAllowedToSaveNotification(user, run, workgroup)) {
        return new ArrayList<Notification>();
      }
    } else if (!user.isAdmin() && !runService.hasRunPermission(run, user, BasePermission.READ)) {
      return new ArrayList<Notification>();
    }
    return vleService.getNotifications(id, runId, periodId,
        toWorkgroupId, groupId, nodeId, componentId);
```

The changed code that doesn't return the notifications has the "else if" changed to "if".
```
    if (toWorkgroup != null) {
      if (isStudentAndNotAllowedToSaveNotification(user, run, toWorkgroup)) {
        return new ArrayList<Notification>();
      }
    }
    if (!user.isAdmin() && !runService.hasRunPermission(run, user, BasePermission.READ)) {
      return new ArrayList<Notification>();
    }
    return vleService.getNotifications(id, run, periodId, toWorkgroup, groupId, nodeId,
        componentId);
```

Copying a project in the Authoring Tool shows a popup error but the project still gets copied. This popup error does not happen on develop or PROD. I couldn't figure out why the popup error is happening.

All the other endpoints I tested seemed to work.

**Comment by hirokiterashima** [comment]
I reverted the logic changes in NotificationController.getNotifications() and also the changes in AuthorAPIController.copyProject. I think this problem may be fixed by refactoring the the call to ```projectService.copyProject(projectId, user);``` to take in a Project object. I'll work on this in a separate branch.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
