### PR TITLE
feat(Run): Increase possible runcodes

### LINKED ISSUE #149: Increase possible runcodes
### Description

Increase runcode possibilities from 86K now to at least 860K. This will lessen runcode collision and result in faster run creation time.

### PR DESCRIPTION
**Pull request by hirokiterashima**
## Changes
- Add 54 new prefixes, bringing total to 140.
- Increase digit suffix from 3-length to 4-length

## Test Prep
- Copy ```runcode_prefixes_en``` from application-sample.properties to application-dockerdev.properties
- Restart WISE-API

## Test
- Create new runs and verify that the runcodes use the [animal prefix][4-digit suffix] format.
 
Closes #149

### CODE REVIEW

**Review by geoffreykwan — CHANGES_REQUESTED** [review]
1. Should the prefixes be completely alphabetized? Right now it's not alphabetized within a given starting letter like "Boa,Bee,Bat".

2. Student can't add a run if the run code contains 4 digits because the "Add Unit" regex still only allows 3 digits in AddProjectDialogComponent in WISE-Client add-project-dialog.component.ts.

**Comment by hirokiterashima** [comment]
Made the changes to WISE-Client to accept 4-digit runcode suffix here: https://github.com/WISE-Community/WISE-Client/pull/659

Also alphabetized runcodes.

**Review by geoffreykwan — APPROVED** [review]
Looks good.

**Pull request merged**
